package drakonli.dota2.hero_grid_customizer.application.view_handler.restore;

import drakonli.dota2.hero_grid_customizer.application.view_handler.ParameterlessViewActionHandlerInterface;

public interface RestoreButtonHandlerInterface extends ParameterlessViewActionHandlerInterface
{
}
