package drakonli.dota2.hero_grid_customizer.application.view_handler.load;

import drakonli.dota2.hero_grid_customizer.application.view_handler.ParameterlessViewActionHandlerInterface;

public interface LoadButtonHandlerInterface extends ParameterlessViewActionHandlerInterface
{
}
